apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: cyvive-prepull
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: cyvive-prepull
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10
  template:
    metadata:
      labels:
        name: cyvive-prepull
    spec:
      initContainers:
      - name: prepull
        image: docker
        command: ["docker", "pull", "gcr.io/taylored-technology/cyvive:kubernetes"]
        volumeMounts:
        - name: docker
          mountPath: /var/run
      volumes:
      - name: docker
        hostPath:
          path: /var/run
      containers:
      - name: pause
        image: gcr.io/google_containers/pause

