site_name: Cyvive <b>any</b> Cloud
site_descripiton: Immutable Change
site_author: cyvive.com
site_url: https://www.cyvive.com

copyright: '&copy; Taylored Technology 2017-Current'
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'grey'
    accent: 'lime'
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'
  feature:
    tabs: true
extra:
  search:
    language: 'en'
  manifest: 'manifest.webmanifest'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - meta

extra_javascript:
  - 'javascripts/extra.js'

nav:
  - 'Why Cyvive?':
    - 'Why Cyvive?': 'index.md'
    # - 'Solutions': 'solutions/index.md'
    - 'Architecture':
      - 'Overview': 'architecture/index.md'
      - 'Cirro': 'architecture/cirro.md'
      - 'Culumo': 'architecture/culumo.md'
      - 'Strato': 'architecture/strato.md'
      - 'Nimbo': 'architecture/nimbo.md'
    # - 'Pricing': 'pricing.md'
    - 'Resources':
      - 'EcoSystem': 'resources/ecosystem.md'
      - 'FAQ': 'resources/faq/index.md'
      - 'Foggy Ubiquity': 'http://www.foggyubiquity.com/language'
      # - 'Getting Started': 'resources/operation/index.md'
      - 'Support': 'resources/support.md'
    - 'Terms & Conditions': 'license.md'
  # - 'Solutions':
  #   - 'Overview': 'solutions/index.md'
    # - 'Immutability': 'solutions/immutability.md'
    # - 'Change Control': 'solutions/change-control.md'
    # - 'Disaster Recovery': 'solutions/disaster-recovery.md'
    # - 'Sandbox Environments': 'solutions/sandbox-environments.md'
    # - 'Isolation': 'solutions/isolation.md'
    # - 'Kubernetes': 'solutions/kubernetes.md'
  - 'Architecture':
    - 'Overview': 'architecture/index.md'
    - 'Cirro': 'architecture/cirro.md'
    - 'Culumo': 'architecture/culumo.md'
    - 'Strato': 'architecture/strato.md'
    - 'Nimbo': 'architecture/nimbo.md'
  - 'Pricing': 'pricing.md'
  - 'Resources':
    # - 'Getting Started':
    #   - 'Developer': 'resources/operation/developer.md'
    #   - 'Govenor': 'resources/operation/govenor.md'
    #   - 'Install': 'resources/operation/installing.md'
    # - 'Whitepapers': 'resources/white-papers/index.md'
    # - 'Case Study': 'resources/case-study/index.md'
    - 'Foggy Ubiquity': 'http://www.foggyubiquity.com/language'
    - 'EcoSystem': 'resources/ecosystem.md'
    - 'FAQ': 'resources/faq/index.md'
    - 'Support': 'resources/support.md'
