site_name: Cyvive
site_descripiton: Immutable Change
site_author: cyvive.io
site_url: https://www.cyvive.io

copyright: '&copy; Taylored Technology 2018-Current'
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'grey'
    accent: 'lime'
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'
  feature:
    tabs: true
extra:
  search:
    language: 'en'
  manifest: 'manifest.webmanifest'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - meta

extra_javascript:
  - 'javascripts/extra.js'

pages:
  - 'About': 
    - 'Cyvive': 'index.md'
    - 'Platform': 'platform/index.md'
    - 'EcoSystem': 'ecosystem/index.md'
    - 'Governance': 'governance/index.md'
    - 'Terms & Conditions': 'license.md'
  - 'Platform':
    - 'Understanding': 'platform/index.md'
  - 'EcoSystem':
    - 'Understanding': 'ecosystem/index.md'
  - 'Governance':
    - 'Understanding': 'governance/index.md'
    - 'Case for Governance': 'governance/case-for.md'
    - 'Usage':
      - 'Developer': 'governance/usage/developer.md'
      - 'Govenor': 'governance/usage/govenor.md'
    - 'Configuration':
      - 'Suite of Services': 'governance/configuration/suites.md'
      - 'MicroService': 'governance/configuration/index.md'
      - 'NanoService': 'governance/configuration/index.md'
      - 'Templates': 'governance/configuration/templates.md'
        #  - 'Blog':
        #- 'itstarts': 'blog/itstarts.md'



